---
- name: Leave the following alone - logging logic
  block:

    - name: Capture and log error
      set_fact:
        grader_output_message: '{{ "Section: " + ( section_number | string)  + ", " + inventory_hostname + ", " + task_description_message }}'
      delegate_to: localhost

    - name: Log event to log file
      import_role:
        name: ftl_run_log_grade_to_log

  delegate_to: localhost
  when: r_state.changed
...
