environment:toc:

== Overview

`lm-injector` clones the lm Repo into an existing environemnt and configures the target machine to be able to grade labs. Originally designed to work with AgnosticD lm can work with any environment where the appropriate Ansible credentials can be supplied.

=== What does `lm-injector` do:

. Create grading virtualenv - isolating lm from student configuration
. Clones the lm Repo, containing graders etc  onto the grader host
. Create custom facts about students, course(s), for simple reporting
. Installs grader scripts etc.

=== Usage

. Add lm to your config by
** Choosing a *grader host* where lm will be installed, typically a machine a student works on.
*** `bastion`
*** Some form of client VM
** Calling the lm-injector role
*** For example *config* `three-tier-app` adds in in `pre_software.yml`
+
[source,yaml]
----
- name: Inject and configure lm on bastion as grader host
  hosts: bastions
  become: true
  roles:
    - lm-injector
  tags:
    - step004
    - lm-injector
----
. *OPTIONAL* To provide accurate reporting provide a `student_login` var
** For agnosticd users working with CloudForms, in your deployer scripts:
+
[source,bash]
----
export OPENTLC_STUDENT=${USER:-unknown-student}                   <1>


            ansible-playbook                                  \
                ${DEPLOYER_REPO_PATH}/main.yml                \
                -e ANSIBLE_REPO_PATH=${DEPLOYER_REPO_PATH}    \
                -e guid=${GUID}                               \
                -e env_type=${ENVTYPE}                        \
                -e key_name=${KEYNAME}                        \
                -e email=${USEREMAIL}                         \
                -e student_login=${OPENTLC_STUDENT}           \   <2>
----
+
* *1* Assign the CloudForms `--user` argument to an *ENV VAR*
* *2* Use *1* to pass to `ansible` via `-e`

NOTE: Failing to do this will *NOT* result in failure as `student_login` defaults to `john-doe` in the the roles `defaults/main.yml`.

=== Notes

Adding, or updating, the `lm-injector` role to your project:

. Create a requirements.yml, with the correct version tag:
+
[source,yaml]
----

---
# External role to setup grader host virtualenv and lm grading infra

- src: https://github.com/redhat-gpte-devopsautomation/lm-injector
  name: lm-injector
  version: v0.5
----
Use `ansible-galaxy` to install, (substituting your roles directory path if necessary).
+
[source,bash]
----
ansible-galaxy install -r requirements.yml -p roles
----
