
- name: infra-ec2-wait_for_linux_hosts
  hosts:
    - all:!windows
  become: true
  gather_facts: no
  roles:
  - { role: "infra-ec2-wait_for_linux_hosts" }

###############     Play for solutions  ###############
- import_playbook: ./solve_section1.yml
  when: solve == "true"

###############     Play1 for grade     ###############
- hosts: bastion
  become: yes
  tasks:
  - name: dict_facts playbook
    stat:
      path: /home/devops/ansible_implementation/dict_facts.yml
    register: dict_facts
  - name: Fail
    debug:
      msg: "FAILED: playbook is not present"
    when: dict_facts.stat.exists != true
  - name: pass
    debug:
      msg: "Success: playbook pressent" 
    when: dict_facts.stat.exists == true
  - name: dict_pars playbook
    stat:
      path: /home/devops/ansible_implementation/dict_pars.yml
    register: dict_pars
  - name: Fail
    debug:
      msg: "FAILED: playbook is not present"
    when: dict_pars.stat.exists != true
  - name: Pass
    debug:
      msg: "Success: playbook pressent" 
    when: dict_pars.stat.exists == true