---
- name: Grade lab 04_1 of ocp4_advanced_deployment
  hosts: localhost
  gather_facts: false
  become: false
  environment:
    KUBECONFIG: "{{ lookup('env', 'HOME') }}/openstack-upi/auth/kubeconfig"
  tasks:
    - name: Check the worker machinesets
      include_role:
        name: grader_check_ocp_resource
      vars:
        task_description_message: Check that the correct MachineSet objects exist
        resource_api_version: machine.openshift.io/v1beta1
        resource_kind: MachineSet
        resource_name: "{{ item }}"
        resource_namespace: "openshift-machine-api"
        kubeconfig: "{{ lookup('env', 'HOME') }}/openstack-upi/auth/kubeconfig"
        student_error_message: "One or more MachineSet missing"
        validate_certs: False
        resource_definition_checks:
          - error_message: The proper number of replicas are not ready
            json_query: "status.replicas"
            value: 1
      loop:
        - general-purpose-1a
        - general-purpose-1b
        - infra-1a
