
- name: infra-ec2-wait_for_linux_hosts
  hosts:
    - all:!windows
  become: true
  gather_facts: no
  roles:
  - { role: "infra-ec2-wait_for_linux_hosts" }

###############     Play for solutions  ###############
- import_playbook: ./solve_section1.yml
  when: solve == "true"

###############     Play1 for grade     ###############
- name: Grade Lab01
  hosts: all:!bastions
  gather_facts: no
  tasks:
  - name: Verify devops user is created
    shell: "grep devops /etc/passwd | cut -d: -f1"
    register: user_created
  - name: set grade to fail
    debug:  
      msg: "FAIL : devops user does not exist."
    when: user_created.stdout != "devops"

  - name: set grade to Pass
    debug: 
      msg: "PASS :  devops user exists."
    when: user_created.stdout == "devops"

  - name: Verify /etc/motd has content
    shell: "cat /etc/motd"
    register: motd

  - name: set grade to fail
    debug:
      msg: "FAIL : /etc/motd missing content. "
    when: motd.stdout != "Managed by Ansible"

  - name: set grade to Pass
    debug:
      msg: "PASS : /etc/motd missing content. "
    when: motd.stdout == "Managed by Ansible"
  