  
- name: infra-ec2-wait_for_linux_hosts
  hosts:
    - all:!windows
  become: true
  gather_facts: no
  roles:
  - { role: "infra-ec2-wait_for_linux_hosts" }

###############     Play for solutions  ###############
- import_playbook: ./solve_section1.yml
  when: solve == "true"

###############     Play1 for grade      ###############
- name: Grade Lab03
  hosts: apps
  gather_facts: no
  tasks:
  - name: Gather Facts
    setup:
      filter: ansible_local

  - name: Fail if custom fact is not defined
    debug: 
      msg: "FAIL : custom facts are not setup correctly."
    when: 
      ( ansible_facts.ansible_local.custom is not defined) 

  - name: Fail if custom facts are incorrect
    debug: 
      msg: "FAIL : custom facts are not setup correctly."
    when: 
      ( ansible_facts.ansible_local.custom     is            defined ) and (
      ( ansible_facts.ansible_local.custom.general.package != "httpd" ) or 
      ( ansible_facts.ansible_local.custom.general.service != "httpd" ) or
      ( ansible_facts.ansible_local.custom.general.state != "started" ) )
  
  - name: Pass if custom facts are defined and correct
    debug: 
      msg: "PASS : custom facts are setup correctly."
    when: 
      ( ansible_facts.ansible_local.custom     is            defined  ) and
      ( ansible_facts.ansible_local.custom.general.package == "httpd" ) and
      ( ansible_facts.ansible_local.custom.general.service == "httpd" ) and
      ( ansible_facts.ansible_local.custom.general.state == "started" ) 

  - name: Check httpd service status
    service:
      name: httpd
    register: httpd 

  # - debug: var=httpd

  - name: Fail if httpd service is not started
    debug: 
      msg: "FAIL : httpd service is not started" 
    when: ( httpd.status.UnitFileState is not defined ) or
          ( httpd.status.ActiveState != "active" )

  - name: Pass if httpd service is started
    debug: 
      msg: "PASS : httpd service is started" 
    when: ( httpd.status.UnitFileState is defined ) and
          ( httpd.status.ActiveState == "active" ) 
