---
- name: Run grader
  hosts: bastions
  gather_facts: false
  become: false
  vars_files:
    - /home/devops/materials/access_details.yml
  
  tasks:
##### Gitlab project webhook check #####

    - name: List gitlab  projects
      uri:
        url: http://{{ access_details.gitlab_hostname }}/api/v4/projects/
        method: GET
        headers:
          PRIVATE-TOKEN: "{{ access_details.gitlab_root_token }}"
      register: gitlab_project_list

    - name: Get gitlab project id
      set_fact:
        gitlab_project_id: '{{ item.id }}'
      loop: "{{ gitlab_project_list.json }}"
      when: 'item.name == "gitops-lab"'

    - name: Print gitlab project id for gitops-lab project
      debug:
        var: gitlab_project_id
        verbosity: 2

    - name: List gitlab webhook
      uri: 
        url: http://{{ access_details.gitlab_hostname }}//api/v4/projects/{{ gitlab_project_id }}/hooks/
        method: GET
        headers:
          PRIVATE-TOKEN: "{{ access_details.gitlab_root_token }}"
      register: gitlab_webhook_list

    - set_fact:
        gitlab_webhook_urls: "{{ gitlab_webhook_urls | d([]) + [ item.url ] }}"
      loop: "{{ gitlab_webhook_list.json }}"
           
    - debug:
        msg: "{{ gitlab_webhook_urls }}"
        verbosity: 2
        
##### Result for Gitlab webhook #####
    - name: "Success - set fact"
      set_fact:
        success: true
      when: gitlab_webhook_urls | d('') | length > 1

    - name: "No Success - set fact"
      set_fact:
        success: false
      when: gitlab_webhook_urls | d('') | length  <= 1

    - name: Import logging role
      import_role:
        name: ftl_run_log_grade_to_log
      vars:
        task_description_message: "Check if gitlab project repo has 2 webhooks"


##### Credentials check #####  
    - name: List Credentials
      uri: 
        url: https://{{ access_details.tower_hostname }}/api/v2/credentials/
        user: "{{ access_details.tower_admin_user }}"
        password: "{{ access_details.tower_admin_password }}"
        method: GET
        force_basic_auth: yes
        validate_certs: false
        body_format: json
        status_code: 200
      register: credential_list

    - set_fact:
        tower_gitlab_token_credential: "{{  item.name }}"
      loop: "{{ credential_list.json.results }}"
      when: '"gitlab_token" in item.name'

    - debug: 
        msg: "{{ tower_gitlab_token_credential }}"
        verbosity: 2

##### Result for Tower gitlab token #####
    - name: "Success - set fact"
      set_fact:
        success: true
      when: tower_gitlab_token_credential | d('') | length > 0

    - name: "No Success - set fact"
      set_fact:
        success: false
      when:  tower_gitlab_token_credential | d('') | length == 0
      
    - name: Import logging role
      import_role:
        name: ftl_run_log_grade_to_log
      vars:
        task_description_message: "Check if Ansible Tower has gitlab token credential"

#### Tower webhooks       
    - name: List Jobtemplate
      uri: 
        url: https://{{ access_details.tower_hostname }}/api/v2/job_templates/
        user: "{{ access_details.tower_admin_user }}"
        password: "{{ access_details.tower_admin_password }}"
        method: GET
        force_basic_auth: yes
        validate_certs: false
        body_format: json
        status_code: 200
      register: jobtemplate_list

    - name: find id for Prod job template
      set_fact: 
        test_job_template_id: "{{ item.id }}"
      loop: "{{ jobtemplate_list.json.results }}"
      when: '"Test" in item.name' 

    - name: find id for Prod job template
      set_fact: 
        prod_job_template_id: "{{ item.id }}"
      loop: "{{ jobtemplate_list.json.results }}"
      when: '"Prod" in item.name'    
         
    - name: Jobtemplate webhook key
      loop: "{{ jobtemplate_list.json.results }}"
      uri: 
        url: https://{{ access_details.tower_hostname }}/api/v2/job_templates/{{ item.id }}/webhook_key/
        user: "{{ access_details.tower_admin_user }}"
        password: "{{ access_details.tower_admin_password }}"
        method: GET
        force_basic_auth: yes
        validate_certs: false
        body_format: json
        status_code: 200
      register: jt_webhook
           
    - set_fact:
        test_jobtemplate_webhooks : "{{ item.json.webhook_key }}"
      loop: "{{ jt_webhook.results }}"
      when: '"/" + test_job_template_id + "/" in item.url'

    - set_fact:
        prod_jobtemplate_webhooks : "{{ item.json.webhook_key }}"
      loop: "{{ jt_webhook.results }}"
      when: '"/" + prod_job_template_id + "/" in item.url'

##### Result for Tower Job template webhook #####
    - name: "Success - set fact"
      set_fact:
        success: true
      when: test_jobtemplate_webhooks | d('') | length > 0

    - name: "No Success - set fact"
      set_fact:
        success: false
      when:  test_jobtemplate_webhooks | d('') | length == 0
      
    - name: Import logging role
      import_role:
        name: ftl_run_log_grade_to_log
      vars:
        task_description_message: "Check if 'App deployer - Test Env' Job template has webhook enabled"

    - name: "Success - set fact"
      set_fact:
        success: true
      when: prod_jobtemplate_webhooks | d('') | length > 0

    - name: "No Success - set fact"
      set_fact:
        success: false
      when:  prod_jobtemplate_webhooks | d('') | length == 0
      
    - name: Import logging role
      import_role:
        name: ftl_run_log_grade_to_log
      vars:
        task_description_message: "Check if 'App deployer - Prod Env' Job template has webhook enabled"

##### Smote test for Test Env webhook events #####
    - name: Smoke test for Test Env
      uri:
        url: http://{{ groups['testservers'][0] }}/?name=root
        return_content: yes
        status_code: 
          - -1
          - 200
          - 503
      register: test_result

##### Result smoke test for Test Env #####
    - name: "Success - set fact"
      set_fact:
        success: true
      when: '"root redhat /bin/bash /root" in test_result.content'

    - name: "No Success - set fact"
      set_fact:
        success: false
      when: '"root redhat /bin/bash /root" not in test_result.content'
      
    - name: Import logging role
      import_role:
        name: ftl_run_log_grade_to_log
      vars:
        task_description_message: "Check if Test Env website is accessible"

##### Smote test for Prod Env webhook events #####
    - name: Smoke Test for Prod Env
      uri:
        url: http://{{ groups['frontends'][0] }}/?name=root
        return_content: yes
        status_code: 
          - -1
          - 200
          - 503
      register: prod_result
      ignore_errors: yes

##### Result smoke test for Test Env #####
    - name: "Success - set fact"
      set_fact:
        success: true
      when: '"root redhat /bin/bash /root" in prod_result.content'

    - name: "No Success - set fact"
      set_fact:
        success: false
      when: '"root redhat /bin/bash /root" not in prod_result.content'
      
    - name: Import logging role
      import_role:
        name: ftl_run_log_grade_to_log
      vars:
        task_description_message: Check if Prod Env website is accessible


...