---
- name: Searching file for FAIL
  lineinfile:
    path: "{{ grader_working_dir }}/{{ grader_student_report_file }}"
    regex: "^FAIL.*"
    state: absent
  check_mode: true
  register: r_lab_pass

- when: r_lab_pass.changed | bool
  name: Report contains one or more FAILs
  set_fact:
    lab_passed:             false
    student_errors:         "{{ r_lab_pass.found }}"
    report_status_message:  FAILED

- when: not r_lab_pass.changed | bool
  name: Report contains no FAILs
  set_fact:
    lab_passed: true
    student_errors: "{{ r_lab_pass.found }}"
    report_status_message:  SUCCESS

- name: Output lab status and error count
  debug:
    msg:
      - "lab_passed = {{ lab_passed }}"
      - "Error count = {{ student_errors }}"
    verbosity: 2

- name: Finalize lab report with status
  lineinfile:
    line: |+

      {{ report_status_message }}: {{ student_errors }} Errors

    dest: "{{ grader_working_dir }}/{{ grader_student_report_file }}"
    insertafter:  EOF

- when: ftl_report_checksum | default(false)
  name: Add a checksum to grading report
  block: 

    - name: Generate a sha256 checksum of grading report
      stat:
        path: "{{ grader_working_dir }}/{{ grader_student_report_file }}"
        checksum_algorithm: sha256
      register: r_stat

    - name: Sign student grading report
      lineinfile:
        path: "{{ grader_working_dir }}/{{ grader_student_report_file }}"
        line: "{{ r_stat.stat.checksum }}  {{ grader_student_report_file }}"
...
