---
- name: Grade lab 01 01 of Ansible Implementation
  hosts: 3tierapp
  connection: local
  gather_facts: false

  roles:      # All lab tests go here

    - name: Section 3
      role: grader_check_user_exists
      vars:
        user: devops
        student_error_message: User devops does not exist
        task_description_message: Check user devops exists

    - name: Section 3
      role: grader_check_user_exists
      vars:
        user: root
        #section_number: 3.2
        student_error_message: User root does not exist
        task_description_message: Check user root exists

    - name: Section 3
      role: grader_check_user_exists
      vars:
        user: lp
        #section_number: 3.2
        student_error_message: User lp does not exist
        task_description_message: Check user lp exists

    - name: Section 3
      role: grader_check_user_exists
      vars:
        user: devops
        #section_number: 3.2
        student_error_message: User devops does not exist
        task_description_message: Check user devops exists
...
