#!/usr/bin/env bash


if [ $# -ne 2 ];
then  
  echo "Usage: grade-lab course-name lab-number"
  echo
  echo "lab-number in format 03_01"
  exit 1
fi  

COURSE_NAME=$1
LAB_NUMBER=$2

# wrapper script for grading playbook for lab
#

VIRTUALENV=/opt/virtualenvs/venv-grading

# You can set the lm_REPO_HOME var in your environment to point
# to the repo you are developing in
if [ -z "$lm_REPO_HOME" ]
then
    lm_REPO_HOME=/opt/lm-repo-clone/
fi

GRADE_REPORT=/tmp/grading_report.txt
export LOG_FILE=/tmp/opentlc_ansible.log

#
# Clean up - next bit is a job for ansible
# 

if [ -f ${GRADE_REPORT} ]; 
then
  cp  ${GRADE_REPORT} ${GRADE_REPORT}-previous
fi

# Make sure ansible finds the correct roles if it loads a new ansible.cfg

export ANSIBLE_ROLES_PATH=${lm_REPO_HOME}/roles:${lm_REPO_HOME}/roles-lm-runtime
export FILE=${lm_REPO_HOME}/courses/${COURSE_NAME}/ansible.cfg
export DATE=$(date +"%Y%m%d")
export LOG_FILE=/tmp/grading_"$DATE".log

if [ -f $FILE ]; then
   export ANSIBLE_CONFIG=${FILE}
fi

# Activate a protected vurtualenv with all dependencies and it's own ansible

echo "Starting Grading Process"

source ${VIRTUALENV}/bin/activate

( cd ${lm_REPO_HOME};  ansible-playbook main.yml                   \
  -e @vars/global_vars.yml                                          \
  -e course_name=${COURSE_NAME}                                     \
  -e purpose=grade                                                  \
  -e lab_number=${LAB_NUMBER} | ${LOG_FILE} 2>&1 | tee ${LOG_FILE} | sed -n 's/LAB_MANAGER_OUTPUT//p

echo "Finished Grading Process"
echo

cat ${GRADE_REPORT}

echo
echo "Grading Report:        ${GRADE_REPORT}"
echo "Grading Log (ansible): ${LOG_FILE}"
