---
# This grader expects GUID and opentlc_student to be
# set in /opt/ftl-repo-clone/vars/global_vars.yml
  
- name: Grade Homework of OpenShift 4 Advanced Application Deployment ILT
  hosts: localhost
  gather_facts: false
  become: false

  # All lab tests go here
  tasks:
  - name: Print debug output
    debug:
      msg: "Submitting grade for student {{ opentlc_student }} and GUID {{ guid }}."

  - name: "Check that tasks route in {{ guid }}-tasks-prod points to the Green Service"
    include_role:
      name: grader_check_ocp_resource
    vars:
      task_description_message: "Check that tasks route in {{ guid }}-tasks-prod points to the green service"
      resource_api_version: route.openshift.io/v1
      resource_kind: Route
      resource_name: tasks
      resource_namespace: "{{ guid }}-tasks-prod"
      resource_definition_checks:
      - error_message: Tasks route does not point to tasks-green service.
        json_query: "spec.to.name"
        value: "tasks-green"
