---
- name: Check ssh connecivity to hosts aka ansible ping
  hosts: 3tierapp
  connection: local
  gather_facts: false

  roles:      # All lab tests go here

    - name: Section 2
      role: grader_check_ssh_connectivity
      vars:
        student_error_message: Failed to ssh connect to host
        task_description_message: ssh connectivity test aka ping
...
