
- name: infra-ec2-wait_for_linux_hosts
  hosts:
    - all:!windows
  become: true
  gather_facts: no
  roles:
  - { role: "infra-ec2-wait_for_linux_hosts" }

###############     Play for solutions  ###############
- import_playbook: ./solve_section1.yml
  when: solve == "true"

###############     Play1 for grade     ###############
- hosts: support
  gather_facts: false
  tasks:
  - name: Cheeck postfix
    wait_for:
      port: 25
      delay: 10
      state: started
    register: pkg
  - debug: var=pkg
  - fail:
      msg: "FAILED: Mail relay server not configured"
    when: pkg.state != "started"
  - debug:
      msg: "Success: Mail relay server configured"
    when: pkg.state == "started"
