---
# Create the lm virtualenv on grader host
- import_tasks: create-virtualenv.yml

# Insert the lm git repo on grader host
- import_tasks: insert-lm-repo.yml

# Create local facts from student and course metadata
- import_tasks: create-local-facts.yml

# Insert the wrapper scripts called by students
- import_tasks: insert-wrapper-scripts.yml
...
