---
- name: Run lm Init role - initialize grading report data structures
  hosts: localhost
  gather_facts: false
  become: false
  tags:
    - lm-init

  roles:

    - when: purpose == "grade_lab"
      name: rhlearning.lab_manager.lm_run_init

- name: "Import and run the {{ purpose }} playbooks"
  import_playbook: "./courses/{{ course_id }}/lab_{{ lab_id }}/{{ purpose }}.yml"
  tags:
    - lm-grade

- name: Run lm finish role - generate reports and updates
  hosts: localhost
  gather_facts: false
  become: false
  tags:
    - lm-finish

  roles:
    - when: purpose == "grade_lab"
      name: rhlearning.lab_manager.lm_run_finish
...
