---
- name: Grade lab 03_2 of OpenShift 4 Application Deployment
  hosts: localhost
  gather_facts: false
  become: false

  # All lab tests go here
  tasks:
  - name: Set GUID
    set_fact:
      guid: "{{ lookup('env','GUID') }}"
 
  - name: Check that the Deployment Config printenv exists
    include_role:
      name: grader_check_ocp_resource
    vars:
      task_description_message: Check that the Deployment Config `printenv` exists.
      student_error_message: "Deployment Config `printenv` does not exist in project ${GUID}-development."
      resource_api_version: apps.openshift.io/v1
      resource_kind: DeploymentConfig
      resource_name: printenv
      resource_namespace: "{{ guid }}-development"

  # This doesn't work. Not sure why
  # - name: Check that the Deployment Config printenv exists has the correct volumeMounts
  #   include_role:
  #     name: grader_check_ocp_resource
  #   vars:
  #     task_description_message: Check that the Deployment Config `printenv` has the correct volumeMounts definition
  #     resource_api_version: apps.openshift.io/v1
  #     resource_kind: DeploymentConfig
  #     resource_name: printenv
  #     resource_namespace: "{{ guid }}-development"
  #     resource_definition_checks:
  #     - error_message: "Deployment Config `printenv` does not have the correct volumeMount definition."
  #       json_query: "spec.template.spec.containers[0].volumeMounts.[mountPath]"
  #       value: "/downward"
